# Generated by scripts/brew-formula.sh in cintelis/hackernews from the
# checksums of v0.5.0, after verifying their signature with the Cintelis
# release key. Don't edit by hand: the next release replaces it.
class Cintelis < Formula
  desc "CISO AI - Hacker News: a fast Hacker News reader for the terminal"
  homepage "https://github.com/cintelis/hackernews"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cintelis/hackernews/releases/download/v0.5.0/cintelis_0.5.0_darwin_arm64.tar.gz"
      sha256 "dfc4dab5379c0cf5d20341e38e51231b2369bf0af51a365b2fc5d2db572be9eb"
    end
    on_intel do
      url "https://github.com/cintelis/hackernews/releases/download/v0.5.0/cintelis_0.5.0_darwin_amd64.tar.gz"
      sha256 "0b0174107b589503be1e47fc257e61ce041421d1cfcd228776a2e42da09a62ca"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cintelis/hackernews/releases/download/v0.5.0/cintelis_0.5.0_linux_arm64.tar.gz"
      sha256 "4ad7dc8faca8e4260abfc0846fff8c2d38ffaf43294a8edd79ac4c9684a456f0"
    end
    on_intel do
      url "https://github.com/cintelis/hackernews/releases/download/v0.5.0/cintelis_0.5.0_linux_amd64.tar.gz"
      sha256 "ca79ddd4584b3c685f87225394b4676e6d8ca5455f8b54b09c7a066d02e661b1"
    end
  end

  def install
    bin.install "cintelis"
  end

  def caveats
    return unless OS.mac?

    <<~EOS
      To add CISO AI - Hacker News to Launchpad, Spotlight and the Dock, run:
        cintelis install-app
    EOS
  end

  test do
    assert_match "cintelis #{version}", shell_output("#{bin}/cintelis version")
  end
end
