# Generated by scripts/brew-formula.sh in cintelis/hackernews from the
# checksums of v0.4.0, after verifying their signature with the Cintelis
# release key. Don't edit by hand: the next release replaces it.
class Cintelis < Formula
  desc "CISO AI - Hacker News: a fast Hacker News reader for the terminal"
  homepage "https://github.com/cintelis/hackernews"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cintelis/hackernews/releases/download/v0.4.0/cintelis_0.4.0_darwin_arm64.tar.gz"
      sha256 "f236cf259f13375596ad2bdbc11c47c293e650d1f0bd3b3236b4ba9cc9a0fd54"
    end
    on_intel do
      url "https://github.com/cintelis/hackernews/releases/download/v0.4.0/cintelis_0.4.0_darwin_amd64.tar.gz"
      sha256 "5fd89080e6998035c727fccfefb06ffd9aa8faee9ad8593e5eafda37e38e96a1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cintelis/hackernews/releases/download/v0.4.0/cintelis_0.4.0_linux_arm64.tar.gz"
      sha256 "9adc07f18f201628a10b2be3c572473090cc2b2b25ba38a9d385758516934fb8"
    end
    on_intel do
      url "https://github.com/cintelis/hackernews/releases/download/v0.4.0/cintelis_0.4.0_linux_amd64.tar.gz"
      sha256 "ec44ab8992c060e5cc02a3ed7e3418fe646e7bc756d3400099fe8223c3d5df27"
    end
  end

  def install
    bin.install "cintelis"
  end

  test do
    assert_match "cintelis #{version}", shell_output("#{bin}/cintelis version")
  end
end
