# Generated by scripts/brew-formula.sh in cintelis/hackernews from the
# checksums of v0.4.1, after verifying their signature with the Cintelis
# release key. Don't edit by hand: the next release replaces it.
class Cintelis < Formula
  desc "CISO AI - Hacker News: a fast Hacker News reader for the terminal"
  homepage "https://github.com/cintelis/hackernews"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cintelis/hackernews/releases/download/v0.4.1/cintelis_0.4.1_darwin_arm64.tar.gz"
      sha256 "2ae26b3bc3193340af3e84527ab77c24057fcd42b508ee2016abd61c77242d8e"
    end
    on_intel do
      url "https://github.com/cintelis/hackernews/releases/download/v0.4.1/cintelis_0.4.1_darwin_amd64.tar.gz"
      sha256 "c8bdc9cb7cd97b9a2868ea970b1ceed3e67543867f58925e14ed7c1b7925ac86"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cintelis/hackernews/releases/download/v0.4.1/cintelis_0.4.1_linux_arm64.tar.gz"
      sha256 "3428c1006d17b7418b95c7fc306d10eaa52bd3e3e2758490d022f8771bd153aa"
    end
    on_intel do
      url "https://github.com/cintelis/hackernews/releases/download/v0.4.1/cintelis_0.4.1_linux_amd64.tar.gz"
      sha256 "3aa049b34275c2c70ba216dc6e23bac34c86a48a17b55c9d49402c3573f4342d"
    end
  end

  def install
    bin.install "cintelis"
  end

  test do
    assert_match "cintelis #{version}", shell_output("#{bin}/cintelis version")
  end
end
